// Code generated by openapi-transformer. DO NOT EDIT.

use anyhow::Result;
use datadog_api_client::datadogV2::api_downtimes::{DowntimesAPI, GetDowntimeOptionalParams};

use crate::config::Config;
use crate::formatter;

#[derive(clap::Subcommand)]
pub enum Command {
    /// Get a downtime
    ///
    /// Get downtime detail by `downtime_id`.
    Get {
        /// ID of the downtime to fetch.
        downtime_id: String,
        /// Comma-separated list of resource paths for related resources to include in the response. Supported resource
        /// paths are `created_by` and `monitor`.
        #[arg(long)] include: Option<String>,
    },
}

pub async fn run(cfg: &Config, command: Command) -> Result<()> {
    match command {
        Command::Get { downtime_id, include } => get(cfg, downtime_id, include).await,
    }
}

/// Get a downtime
///
/// Get downtime detail by `downtime_id`.
pub async fn get(cfg: &Config, downtime_id: String, include: Option<String>) -> Result<()> {
    let api = crate::make_api!(DowntimesAPI, cfg);
    let mut params = GetDowntimeOptionalParams::default();
    if let Some(v) = include {
        params = params.include(v);
    }
    let resp = api
        .get_downtime(downtime_id, params)
        .await
        .map_err(|e| anyhow::anyhow!("failed to get_downtime: {:?}", e))?;
    formatter::output(cfg, &resp)
}

#[cfg(test)]
mod tests {
    use crate::test_support::*;

    #[tokio::test]
    async fn test_get_ok() {
        let _lock = lock_env().await;
        let mut server = mockito::Server::new_async().await;
        let cfg = test_config(&server.url());
        let _mock = mock_any(&mut server, "GET", r##"{"data": {"attributes": {"created": "2024-01-01T00:00:00+00:00", "display_timezone": "America/New_York", "message": "Message about the downtime", "modified": "2024-01-01T00:00:00+00:00", "monitor_identifier": {"monitor_tags": ["*"]}, "mute_first_recovery_notification": false, "notify_end_states": ["alert", "warn"], "notify_end_types": ["canceled", "expired"], "scope": "env:(staging OR prod) AND datacenter:us-east-1", "status": "active"}, "id": "00000000-0000-1234-0000-000000000000", "type": "downtime"}}"##).await;
        let result = super::get(&cfg, "test".to_string(), None).await;
        assert!(result.is_ok(), "get failed: {:?}", result.err());
        cleanup_env();
    }
}
