// Code generated by openapi-transformer. DO NOT EDIT.

#[path = "downtime.rs"]
pub mod downtime;

use anyhow::Result;

use crate::config::Config;

/// All spec-generated pup commands.
///
/// Re-run the generator to add or remove tags; pup never needs manual changes
/// for new commands.
#[derive(clap::Subcommand)]
pub enum GeneratedCommand {
    /// Manage downtime resources
    Downtime {
        #[command(subcommand)]
        action: downtime::Command,
    },
}

pub async fn run(cfg: &Config, command: GeneratedCommand) -> Result<()> {
    match command {
        GeneratedCommand::Downtime { action } => downtime::run(cfg, action).await,
    }
}
